"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# Use custom format:
format='''
[$username]()[$directory]()[$character]()
'''

# Prompt symbols 
[character]
success_symbol = "[❭](bold green)"
error_symbol = "[❭](bold red)"

[directory]
format = "[]($style)[[ ](bg:#29294f fg:blue)$path](bg:#29294f fg:white)[ ]($style)"
style = "bg:bg fg:#29294f"
truncation_symbol = '../'

[git_branch]
format = "[]($style)[[ ](bg:bright-black fg:red)$branch](bg:bright-black fg:white)[]($style)"
style = "fg:bright-black"
