format = """
[](fg:#372951 bg:bg)\
$directory\
[](fg:#372951 bg:#906bba)\
$username\
[ ](fg:#906bba bg:bg)\
"""
# [](fg:#2f2446 bg:#394260)\
# 

[directory]
style = "fg:#c1caf5 bg:#372951"
format = "[](bg:#302446 fg:cyan)[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[ \\$](green)"
error_symbol = "[ \\$](red)"

[username]
style_user = "fg:fg bg:#8262a7"
style_root = "fg:fg bg:#8262a7"
show_always = true
format = "[  ](fg:black bg:#906bba)[$user ](fg:black bg:#906bba)"
