"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# Use custom format:
format="$directory$character"

# Prompt symbols 
[character]
success_symbol = "[❭](bold green)"
error_symbol = "[❭](bold green)"

[directory]
format = "[]($style)[[ ](bg:bright-black fg:blue)$path](bg:bright-black fg:white)[ ]($style)"
read_only = ""
read_only_style = 'bg: bright-black fg:blue'
style = "bg:#11111f fg:bright-black"
truncation_symbol = '.'

[git_branch]
format = "[]($style)[[ ](bg:bright-black fg:red)$branch](bg:bright-black fg:white)[]($style)"
style = "fg:bright-black"
