# get completions
"$schema" = 'https://starship.rs/config-schema.json'
#[┌───── ](normal #8ec07c)[$username](bold)[ in ]()[$directory](bold)[$git_branch]()
#[└─ ](normal #8ec07c)[$character](bold)"""

format = """
[$directory](bold)[$character](bold)
"""

add_newline = true

[directory]
style = 'bold   yellow'

[character]
# ❭
success_symbol = '[❭](bold yellow)'
error_symbol = '[❭](bold yellow)'

[username]
style_user = 'bold #d3869b'
style_root = 'bold #ea6962'
format = '[$user](bold #d3869b)'
show_always = true

[git_branch]
style = 'bold #7daea3'
#format = 'on [$git_branch](bold)'
[package]
disabled = true


