format = """
[](fg:#281c41 bg:bg)\
[   ](bg:#281c41 fg:#bc91eb)\
[](fg:#281c41 bg:#3c2b55)\
$directory\
[](fg:#3c2b55 bg:#8961b4)\
$username\
[ ](fg:#8961b4 bg:bg)\
"""

right_format = """
$git_branch\
"""
# [](fg:#2f2446 bg:#394260)\
# [](fg:#382951 bg:bg)\
#  

[directory]
style = "fg:#d9baf6 bg:#3c2b55"
format = "[](bg:#382951 fg:cyan)[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[ ❭](purple)"
error_symbol = "[ ❭](red)"

[username]
#style_user = "fg:fg bg:#8262a7"
#style_root = "fg:fg bg:#8262a7"
show_always = true
format = "[  ](fg:black bg:#8961b4)[$user ](fg:black bg:#8961b4)"

[time]
format = "[ ](fg:black bg:#7c7abb)[$time ](fg:black bg:#7c7abb)"
disabled = false
use_12hr = true

[git_branch]
format = "[](fg:#605292)[ $branch ](fg:#605292)"
