"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# Use custom format:
format = '''
[╭───── ](purple)[$username]()[$hostname]()[$directory]()
[╰─ ](purple)[$character]()
'''

[username]
show_always = true
disabled = false
style_user = "bg:bg fg:blue"
style_root = "bg:bg fg:blue"
format = "[\\[]() [$user](bg:bg fg:blue)[@](bg:bg fg:fg)"

[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[hostname]
ssh_only = false
ssh_symbol = ''
trim_at = ''
disabled = false
style = "yellow"
format = "[$hostname]($style)"

[directory]
style = 'purple'
read_only = ''
truncation_symbol = ''
format = " [$path]($style) [\\]]()"
