format = """
[](fg:#281d3a bg:bg)\
[   ](bg:#261c37 fg:#b58fe0)\
[](fg:#281d3a bg:#3a2a53)\
$directory\
[](fg:#3a2a53 bg:#8861b4)\
$username\
[ ](fg:#8861b4 bg:bg)\
"""
# [](fg:#2f2446 bg:#394260)\
# [](fg:#382951 bg:bg)\
#  

[directory]
style = "fg:#c1caf5 bg:#3a2a53"
format = "[](bg:#382951 fg:cyan)[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[character]
success_symbol = "[ ❭](purple)"
error_symbol = "[ ❭](red)"

[username]
#style_user = "fg:fg bg:#8262a7"
#style_root = "fg:fg bg:#8262a7"
show_always = true
format = "[  ](fg:black bg:#8861b4)[$user ](fg:black bg:#8861b4)"

[time]
format = "[ ](fg:black bg:#7c7abb)[$time ](fg:black bg:#7c7abb)"
disabled = false
use_12hr = true
